### PR TITLE
Add convenience functions useful for active learning [WIP]

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
Adds two convenience functions to perform active learning style training to BuiltinEnsemble
One of them outputs the energies of the individual models (reusing the aev's via BuiltinEnsemble)
The other one calculates the rho coefficients directly for a given batch
Also add capability of directly outputting shifted atomic energies

All functions are jittable, will add tests soon.

### CODE REVIEW

**Comment by IgnacioJPickering** [comment]
Hey @farhadrgh , any idea of why it is mypy is failing in this PR? there seems to me to be no problem... I didn't even touch that file, I don't understand why this would fail

**Comment by IgnacioJPickering** [comment]
It should be fine now, I will add some tests and see if this can be merged asap, since kate asked me to code some of these for her work.

**Review by zasdfgbnm — APPROVED** [review]
The code quality generally LGTM. Since I don't have much knowledge of how the active learning work, I will stamp my approval, and let the roitberg group decide whether this should be merged immediately or needs further review from someone else.

**Review by farhadrgh — APPROVED** [review]
LGTM

**Comment by IgnacioJPickering** [comment]
@farhadrgh any idea why tests are not running?

**Comment by farhadrgh** [comment]
> @farhadrgh any idea why tests are not running?

No, that's weird! It is taking too long

**Comment by IgnacioJPickering** [comment]
@farhadrgh  Soooo looks like github had disabled all the workflows in my fork for some reason. It sent me emails saying it had disabled the workflows. I recommend you take a look at your forks because if I understood correctly all forks now behave like that by default.

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering does this PR help on https://github.com/aiqm/torchani/issues/505#issuecomment-722623218 and if so, could this be exported to `aiqm/torchani`?

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm Yeah, it should make it easy for a user to access individual energies with this PR, but not the "latent space representation" I'm not sure what he means by that, if he means the activations of the layer closer to the output then it doesn't directly help with that.

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering My understanding of the "latent space of the molecule representation" that @hadim refers to the AEV, but I am not sure. Does this PR contain something that should only be internal to the roitberg group, or is it OK to share it outside? My suggestion is to cherry-pick this commit and open a PR at aiqm/torchani and asks @mhellstr and @hadim about what they think.

**Comment by hadim** [comment]
I could have been more explicit indeed. By latent space, as @IgnacioJPickering said, I mean the activations of the layer closer to the output for every atom.

**Pull request merged**
