### PR TITLE
Add farhadh/zasdfgbnm changes

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
This adds the latest changes to the public upstream made by @farhadrgh and @zasdfgbnm 
Unfortunately I found an issue when testing this. It seems that since the files inside resources/ are now not in the .gitignore then git tracks the changes that happen to the files when they are modified after extraction.This happens in both this PR and the current public upstream (aiqm/torchani).

Any idea on how to fix this? it is possible to just touch up the gitignore and checkout the files before doing PR's in the future, but it is uncomfortable. It would be ideal if git could somehow keep a copy of the files frozen but not track further changes.

(to reproduce just clone a new repo, install in a clean conda env and execute energy_force.py for instance)

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Are you saying that after you run the test, the placeholders in the source repo will be changed to a real file? As a workaround, does it make sense to install torchani by `pip install .` instead of `pip install -e .`? This would copy the whole torchani package to python path, and changes will not be make inside the development directory. But the disadvantage of this approach is you will need to rerun `pip install .` everything when you modify anything.

**Comment by zasdfgbnm** [comment]
`torch.jit.Final` is causing failures. I recently fixed the failures on 3.8 https://github.com/pytorch/pytorch/pull/39568, but on 3.6 there is really no easy solution. Would it make sense to just remove all the `torch.jit.Final` from TorchANI?

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm Looks like this can be avoided by running git update-index 
https://stackoverflow.com/questions/55860925/git-skip-worktree-on-all-tracked-files-inside-directory-and-its-subdirectories

Yes, I noticed the issue with Final when doing some stuff with the ONNX support. Final is actually not needed right? it supposedly only adds some performance improvements for JIT

**Comment by IgnacioJPickering** [comment]
We can either remove Final altogether, remove support for 3.6, or put that stuff inside __constants__ that last one should also work but be less explicit?

**Comment by zasdfgbnm** [comment]
> @zasdfgbnm Looks like this can be avoided by running git update-index
Great! I didn't know that.
> Yes, I noticed the issue with Final when doing some stuff with the ONNX support. Final is actually not needed right? it supposedly only adds some performance improvements for JIT
Yeah, I think it is safe to remove it.
> We can either remove Final altogether, remove support for 3.6, or put that stuff inside constants that last one should also work but be less explicit?
If I remember correctly, `constants` is deprecated? Maybe just remove Final altogether. The benefit of Final is low, but dropping 3.6 support sounds bad.

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering Is there a reason why this is is not merged yet? The `deploy-test-pypi` can not be fixed because github secrets are not allowed on PRs from forks, so you have to use your admin superpower to force merge this.

**Review by farhadrgh — APPROVED** [review]
LGTM, Sorry for the delay!

**Comment by IgnacioJPickering** [comment]
@farhadrgh @zasdfgbnm  This is strange, it is still not allowing me to merge due to deploy-test-pypi, this didn't use to be required for this repo I think, no idea what happened. Do you know how to change this?

**Comment by farhadrgh** [comment]
Can you manually uncheck the test in the branch protection plan: https://github.com/roitberg-group/torchani/settings/branches

**Comment by IgnacioJPickering** [comment]
@farhadrgh Seems like there is not any way to fine tune the modules as they are written right now but it should be possible if I change the name of the job I think

**Comment by IgnacioJPickering** [comment]
@farhadrgh works fine now!

**Pull request merged**
