### PR TITLE
Latest torchani changes

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
Merge latest aiqm/torchani changes into the dev version.
(Probably from now on we should freeze aiqm/torchani and work here)

### CODE REVIEW

**Comment by IgnacioJPickering** [comment]
@farhadrgh @yueyericardo hey why does lgtm not run here?

**Comment by farhadrgh** [comment]
> @farhadrgh @yueyericardo hey why does lgtm not run here?



> @farhadrgh @yueyericardo hey why does lgtm not run here?

Can't you merge master of Torchani with roitberg_group/torchani?

**Comment by IgnacioJPickering** [comment]
@farhadrgh no, I couldn't do that, the issue is that aiqm/torchani doesn't have the stuff in the readme that you added

**Comment by IgnacioJPickering** [comment]
So when I tried to merge it it says "the branch you are trying to merge is not updated" and wont allow me unless I modify aiqm/torchani to have those changes in the readme

**Comment by yueyericardo** [comment]
> @farhadrgh @yueyericardo hey why does lgtm not run here?

Maybe we need to add this repo to https://lgtm.com ?

**Comment by IgnacioJPickering** [comment]
If you want give it a try and see if you manage to do it

**Comment by IgnacioJPickering** [comment]
@yueyericardo Yes, I just did that

**Comment by IgnacioJPickering** [comment]
@yueyericardo lgtm was not installed for roitberg-group so I installed it

**Comment by farhadrgh** [comment]
> So when I tried to merge it it says "the branch you are trying to merge is not updated" and wont allow me unless I modify aiqm/torchani to have those changes in the readme

Ah! this makes it difficult each time we want to update

**Comment by IgnacioJPickering** [comment]
@farhadrgh this is why I said maybe its best to freeze the public torchani and work here

**Pull request merged**
